# -*- coding: utf-8 -*-
"""house_predicting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RlBJbqZ6a8BbddXEELZrF1X-P1hILgCh
"""

!pip install kaggle

from google.colab import files
files.upload()  # Upload your kaggle.json file here

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle competitions download -c house-prices-advanced-regression-techniques

import zipfile
with zipfile.ZipFile('house-prices-advanced-regression-techniques.zip', 'r') as zip_ref:
    zip_ref.extractall('house_prices')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the training data
df = pd.read_csv('house_prices/train.csv')

columns_to_check = [
    '1stFlrSF',
    '2ndFlrSF',
    '3SsnPorch',
    'BedroomAbvGr',
    'BsmtFinSF1',
    'MoSold',
    'SalePrice',
    'YrSold'
]

# Get data types of the specified columns
data_types = df[columns_to_check].dtypes
print(data_types)
missing_values = df[columns_to_check].isnull().sum()
print(missing_values)

# Check for missing values in each column
missing_values = df.isnull().sum()
print(missing_values[missing_values > 0])  # Display only columns with missing values

!pip install plotly matplotlib seaborn --quiet

numeric_df = df.select_dtypes(include=['float64', 'int64'])

# Calculate the correlation matrix
correlation_matrix = numeric_df.corr()
price_correlation = correlation_matrix['SalePrice'].sort_values(ascending=False)
print(price_correlation)

columns = ['SalePrice'] + [col for col in correlation_matrix.columns if col != 'SalePrice']
correlation_matrix = correlation_matrix[columns].loc[columns]

# Set the figure size
plt.figure(figsize=(25, 25))

# Create the heatmap
sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap='coolwarm', square=True)

# Add a title
plt.title('Correlation Heatmap')

# Display the heatmap
plt.show()

# Get the unique years from the 'YrSold' column
unique_years = df['YrSold'].unique()

# Sort the years for better readability
sorted_years = sorted(unique_years)

# Display the unique years
print(sorted_years)

"""**Classify Sets:**
 The training, validation, and test sets are created based on the years.
**Remove Columns: **
The drop method is called on each set to remove MoSold and YrSold.
**Separate Inputs and Targets:**
After removing the columns, the input features (X_*) and target variable (y_*) are defined for each set.

"""

train_set = df[df['YrSold'].isin([2006, 2007])]
val_set = df[df['YrSold'].isin([2008])]
test_set = df[df['YrSold'].isin([2009, 2010])]

# Remove the specified columns from each set
train_set = train_set.drop(columns=['MoSold', 'YrSold'])
val_set = val_set.drop(columns=['MoSold', 'YrSold'])
test_set = test_set.drop(columns=['MoSold', 'YrSold'])

# Separate input features and target variable for each set
# Separate input features and target variable for each set with copies
X_train, y_train = train_set.drop(columns='SalePrice').copy(), train_set['SalePrice'].copy()
X_val, y_val = val_set.drop(columns='SalePrice').copy(), val_set['SalePrice'].copy()
X_test, y_test = test_set.drop(columns='SalePrice').copy(), test_set['SalePrice'].copy()

# Display sizes of input and target sets
print("Training Input Size:", X_train.shape[0])
print("Training Target Size:", y_train.shape[0])
print("Validation Input Size:", X_val.shape[0])
print("Validation Target Size:", y_val.shape[0])
print("Test Input Size:", X_test.shape[0])
print("Test Target Size:", y_test.shape[0])

from sklearn.impute import SimpleImputer


num_imputer = SimpleImputer(strategy='mean')

# Identify numerical columns with missing values
num_cols = X_train.select_dtypes(include=[np.number]).columns
num_cols_with_nan = num_cols[X_train[num_cols].isnull().any()]

# Check if there are any numerical columns with missing values
if len(num_cols_with_nan) > 0:
    # Fit the imputer only on numerical columns with missing values
    X_train_imputed = num_imputer.fit_transform(X_train[num_cols_with_nan])
    X_val_imputed = num_imputer.transform(X_val[num_cols_with_nan])
    X_test_imputed = num_imputer.transform(X_test[num_cols_with_nan])

    # Replace imputed numerical data in original DataFrames
    X_train[num_cols_with_nan] = X_train_imputed
    X_val[num_cols_with_nan] = X_val_imputed
    X_test[num_cols_with_nan] = X_test_imputed
else:
    print("No numerical columns with missing values found.")

columns_to_check = ['MoSold', 'SaleType_New', 'YrSold']

# Check for missing columns
missing_columns = [col for col in columns_to_check if col not in categorical_cols]

# Print missing columns
print("Missing columns:", missing_columns)

"""** Scale numeric features**"""

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

# Fit the scaler only on the training data
X_train[num_cols] = scaler.fit_transform(X_train[num_cols])

# Transform validation and test data
X_val[num_cols] = scaler.transform(X_val[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

from sklearn.preprocessing import OneHotEncoder

# Identify categorical columns
categorical_cols = X_train.select_dtypes(include=['object']).columns

# One-hot encode categorical features
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
X_train_encoded = encoder.fit_transform(X_train[categorical_cols])
X_val_encoded = encoder.transform(X_val[categorical_cols])
X_test_encoded = encoder.transform(X_test[categorical_cols])

# Convert encoded arrays back to DataFrame
X_train_encoded = pd.DataFrame(X_train_encoded, columns=encoder.get_feature_names_out(categorical_cols))
X_val_encoded = pd.DataFrame(X_val_encoded, columns=encoder.get_feature_names_out(categorical_cols))
X_test_encoded = pd.DataFrame(X_test_encoded, columns=encoder.get_feature_names_out(categorical_cols))

# Drop original categorical columns and concatenate encoded features back to original DataFrames
X_train.drop(columns=categorical_cols, inplace=True)
X_val.drop(columns=categorical_cols, inplace=True)
X_test.drop(columns=categorical_cols, inplace=True)

# Concatenate the encoded features
X_train = pd.concat([X_train.reset_index(drop=True), X_train_encoded], axis=1)
X_val = pd.concat([X_val.reset_index(drop=True), X_val_encoded], axis=1)
X_test = pd.concat([X_test.reset_index(drop=True), X_test_encoded], axis=1)

# Now X_train, X_val, and X_test contain the final features with one-hot encoding

# Convert to DataFrame for better readability
dtype_df = X_train.dtypes.reset_index()
dtype_df.columns = ['Column Name', 'Data Type']
print(dtype_df)

"""**Code to Save Processed Data**

"""

# Assuming 'SalePrice' is the target column
target_col = 'SalePrice'

# Save processed features and targets to disk
X_train.to_parquet('train_inputs.parquet')
X_val.to_parquet('val_inputs.parquet')
X_test.to_parquet('test_inputs.parquet')
pd.DataFrame(y_train).to_parquet('train_targets.parquet')
pd.DataFrame(y_val).to_parquet('val_targets.parquet')
pd.DataFrame(y_test).to_parquet('test_targets.parquet')

"""**Code to Load Processed Data**"""

# Load processed features and targets from disk
X_train = pd.read_parquet('train_inputs.parquet')
X_val = pd.read_parquet('val_inputs.parquet')
X_test = pd.read_parquet('test_inputs.parquet')
y_train = pd.read_parquet('train_targets.parquet')[target_col]
y_val = pd.read_parquet('val_targets.parquet')[target_col]
y_test = pd.read_parquet('test_targets.parquet')[target_col]

"""**Training the model **"""

from sklearn.linear_model import Ridge

# Initialize the Ridge regression model
model = Ridge()


# Fit the model with training features (X_train) and target variable (y_train)
model.fit(X_train, y_train)

# Print the coefficients as a list
# print(model.coef_.tolist())

# Make predictions on the validation set
predictions = model.predict(X_val)
predictions

"""**model predictions** with the actual target values using a loss function

**Mean Absolute Error (MAE):** Measures the average magnitude of the errors in a set of predictions, without considering their direction. It gives an idea of how far off the predictions are from the actual values.

**Mean Squared Error (MSE):** Measures the average of the squares of the errors. It gives more weight to larger errors, making it sensitive to outliers
"""

from sklearn.metrics import mean_absolute_error, mean_squared_error

# Make predictions on the validation set
predictions = model.predict(X_val)

# Calculate Mean Absolute Error
mae = mean_absolute_error(y_val, predictions)
print("Mean Absolute Error:", mae)

# Calculate Mean Squared Error
mse = mean_squared_error(y_val, predictions)
print("Mean Squared Error:", mse)

"""** Evaluation using optimization technique**"""

from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split, GridSearchCV
import numpy as np

# Function to evaluate and print MAE and MSE
def evaluate_model(y_true, predictions):
    mae = mean_absolute_error(y_true, predictions)
    mse = mean_squared_error(y_true, predictions)
    return mae, mse

# Ensure that y_train is aligned with the number of samples in X_train
if len(y_train) != len(X_train):
    raise ValueError("Mismatch between number of samples in X_train and y_train.")

# Cumulative learning for Ridge regression
def cumulative_ridge(X, y, model, n_splits=5):
    maes = []
    mses = []

    for fold in range(n_splits):
        # Split the data into training and validation sets
        X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(X, y, test_size=0.2, random_state=None)

        # Fit the model on the current training set
        model.fit(X_train_split, y_train_split)

        # Make predictions on the validation set
        predictions = model.predict(X_val_split)

        # Evaluate the model
        mae, mse = evaluate_model(y_val_split, predictions)
        maes.append(mae)
        mses.append(mse)  # Append MSE for averaging later

        # Print the errors for the current fold
        print(f"Fold {fold + 1} - Mean Absolute Error: {mae}, Mean Squared Error: {mse}")

    # Return average MAE, MSE, and last fold MAE
    return np.mean(maes), np.mean(mses), maes[-1]

# Perform cumulative learning for the default Ridge regression model
print("\nCumulative Ridge Regression Model Validation Results:")
ridge_model_default = Ridge()
avg_mae_ridge, avg_mse_ridge, last_fold_mae = cumulative_ridge(X_train, y_train, ridge_model_default)

# Print final evaluation results for default Ridge
print("Average Mean Absolute Error (Default Ridge):", avg_mae_ridge)
print("Average Mean Squared Error (Default Ridge):", avg_mse_ridge)

# Hyperparameter tuning using GridSearchCV for Ridge
alpha_values = np.logspace(-6, 6, 13)
param_grid = {'alpha': alpha_values}
grid_search = GridSearchCV(Ridge(), param_grid, scoring='neg_mean_absolute_error', cv=5)

# Fit the grid search on the training data
grid_search.fit(X_train, y_train)

# Get the best alpha from grid search
optimal_alpha = grid_search.best_params_['alpha']

# Update the existing Ridge model with the optimal alpha
ridge_model_optimized = Ridge(alpha=optimal_alpha)
ridge_model_optimized.fit(X_train, y_train)

# Split the data for validation of the optimized model
X_train_split, X_val_split, y_train_split, y_val_split = train_test_split(X_train, y_train, test_size=0.2, random_state=None)

# Make predictions on the validation set for the optimized model
predictions_ridge_optimized = ridge_model_optimized.predict(X_val_split)

# Evaluate the optimized Ridge model
final_mae_ridge_optimized = mean_absolute_error(y_val_split, predictions_ridge_optimized)
final_mse_ridge_optimized = mean_squared_error(y_val_split, predictions_ridge_optimized)

# Print evaluation results for the optimized Ridge model
print("Optimal Alpha (Optimized Ridge):", optimal_alpha)
print("Final Mean Absolute Error (Optimized Ridge):", final_mae_ridge_optimized)
print("Final Mean Squared Error (Optimized Ridge):", final_mse_ridge_optimized)

# Compare optimized model metrics with the last fold's MAE
print("\nComparison of Metrics:")
print("Improvement in Mean Absolute Error:", last_fold_mae - final_mae_ridge_optimized)
print("Improvement in Mean Squared Error:", avg_mse_ridge - final_mse_ridge_optimized)

# Check if the optimized model has better performance than the last fold
if final_mae_ridge_optimized < last_fold_mae:
    print("The GridSearchCV Ridge model has better performance than the cumulative learning model.")
else:
    print("The optimized Ridge model does not improve upon the cumulative learning model.")

# Prepare to find the best model based on MAE
mae_values = {
    'mae': mae,  # Assuming mae is defined in your other snippet
    'final_mae_ridge_optimized': final_mae_ridge_optimized,
    'last_fold_mae': last_fold_mae
}

# Find the minimum value
min_value_key = min(mae_values, key=mae_values.get)

# Determine the model based on the smallest MAE
if min_value_key == 'final_mae_ridge_optimized':
    model = ridge_model_optimized
    print("The best model is: ridge_model_optimized")
elif min_value_key == 'last_fold_mae':
    model = ridge_model_default
    print("The best model is: ridge_model_default")
else:  # min_value_key == 'mae'
    print("The best model is the original model (Ridge()).")

# Make predictions on the test set
test_predictions = model.predict(X_test)

# Calculate Mean Absolute Error for the test set
test_mae = mean_absolute_error(y_test, test_predictions)
print("Test Mean Absolute Error:", test_mae)

# Calculate Mean Squared Error for the test set
test_mse = mean_squared_error(y_test, test_predictions)
print("Test Mean Squared Error:", test_mse)

"""**store model components**"""

import joblib

# Create a dictionary to store model components
house_price_predictor = {
    'model': model,
    'imputer': num_imputer,
    'scaler': scaler,
    'encoder': encoder,
    'input_cols': X_train.columns.tolist(),
    'target_col': 'SalePrice',
    'numeric_cols': num_cols.tolist(),
    'categorical_cols': categorical_cols.tolist(),
    'encoded_cols': encoder.get_feature_names_out(categorical_cols).tolist()
}

# Save the house price predictor to disk
joblib.dump(house_price_predictor, 'house_price_predictor.joblib')

print("House price predictor saved successfully!")

import joblib
house_price_predictor = joblib.load('house_price_predictor.joblib')

print("House price predictor loaded successfully!")

# Access components
model = house_price_predictor['model']
imputer = house_price_predictor['imputer']
scaler = house_price_predictor['scaler']
encoder = house_price_predictor['encoder']
input_cols = house_price_predictor['input_cols']
target_col = house_price_predictor['target_col']
numeric_cols = house_price_predictor['numeric_cols']
categorical_cols = house_price_predictor['categorical_cols']
encoded_cols = house_price_predictor['encoded_cols']

X_train.dtypes

# Combine X_train with y_train to calculate correlations
y_train_df = pd.DataFrame(y_train, columns=['SalePrice'])
combined_df = pd.concat([X_train, y_train_df], axis=1)

# Select only numeric columns for correlation
numeric_df = combined_df.select_dtypes(include=[np.number])

# Calculate the correlation matrix
correlation_matrix = numeric_df.corr()

# Get the absolute correlation values with SalePrice
correlation_with_target = correlation_matrix['SalePrice'].abs()

# Print correlation values for debugging
print("Correlation values with SalePrice:")
print(correlation_with_target)

# Set a lower threshold for correlation (e.g., 0.1)
threshold = 0.1

# Select features that have a correlation above the threshold
relevant_features = correlation_with_target[correlation_with_target > threshold].index.tolist()

# Remove the target variable from the list
if 'SalePrice' in relevant_features:
    relevant_features.remove('SalePrice')

print("Relevant Features Affecting SalePrice:")
if relevant_features:
    for feature in relevant_features:
        print(feature)
else:
    print("No features found with correlation above the threshold.")

# Calculate mean values for all features in X_train
mean_values = X_train.mean().to_dict()  # Convert to dictionary

# Prepare new input using mean values for features that were used in the model
mean_values_filtered = {key: value for key, value in mean_values.items() if key in model.feature_names_in_}

# Add any necessary one-hot encoded features
if 'SaleType_Oth' in model.feature_names_in_:
    mean_values_filtered['SaleType_Oth'] = 1  # Adjust this based on your encoding

# Debugging: Print the expected and filtered feature sets
print("Expected Features (from model):", model.feature_names_in_)
print("Filtered Mean Values Keys:", mean_values_filtered.keys())

def predict_input(single_input):
    input_df = pd.DataFrame([single_input])

    # Impute missing numeric values for all features
    input_num_cols = input_df.select_dtypes(include=[np.number]).columns.tolist()
    input_df[input_num_cols] = num_imputer.transform(input_df[input_num_cols])

    # Scale numeric features for all features
    input_df[input_num_cols] = scaler.transform(input_df[input_num_cols])

    # One-hot encode categorical features that were relevant
    input_cat_cols = [col for col in categorical_cols if col in input_df.columns]
    if input_cat_cols:
        input_df_encoded = encoder.transform(input_df[input_cat_cols])
        input_df_encoded = pd.DataFrame(input_df_encoded, columns=encoder.get_feature_names_out(input_cat_cols))
        # Concatenate the encoded features back to the input DataFrame
        input_df = pd.concat([input_df.reset_index(drop=True), input_df_encoded.reset_index(drop=True)], axis=1)

    # Prepare final input for prediction
    try:
        X_input = input_df[model.feature_names_in_]  # Use the trained feature names
    except KeyError as e:
        print(f"KeyError: {e}")
        print("Available columns:", input_df.columns.tolist())
        print("Expected features:", model.feature_names_in_)
        return None

    # Make prediction
    pred = model.predict(X_input)[0]

    return pred

# Call the prediction function with the constructed input
prediction = predict_input(mean_values_filtered)
if prediction is not None:
    print("Predicted Sale Price:", prediction)

# Display the structure of the DataFrame
print(df.info())

# Display the first few rows of the DataFrame
print(df.head())

# Check for unique values in categorical columns
for col in df.select_dtypes(include=['object']).columns:
    print(f"{col}: {df[col].unique()}")

def predict_single_input(single_input, model, num_imputer, scaler, encoder, categorical_cols):
    # Convert the single input dictionary to a DataFrame
    input_df = pd.DataFrame([single_input])

    # Separate numerical and categorical columns
    input_num_cols = input_df.select_dtypes(include=[np.number]).columns.tolist()
    input_cat_cols = [col for col in categorical_cols if col in input_df.columns]

    # Impute missing numeric values if necessary
    if input_df[input_num_cols].isnull().any().any():
        input_df[input_num_cols] = num_imputer.transform(input_df[input_num_cols])

    # Scale numeric features
    input_df[input_num_cols] = scaler.transform(input_df[input_num_cols])

    # One-hot encode categorical features
    if input_cat_cols:
        input_df_encoded = encoder.transform(input_df[input_cat_cols])
        input_df_encoded = pd.DataFrame(input_df_encoded, columns=encoder.get_feature_names_out(input_cat_cols))

        # Concatenate the encoded features back to the input DataFrame
        input_df = pd.concat([input_df.reset_index(drop=True), input_df_encoded.reset_index(drop=True)], axis=1)

    # Prepare final input for prediction using the model's expected feature names
    try:
        X_input = input_df[model.feature_names_in_]  # Use the trained feature names
    except KeyError as e:
        print(f"KeyError: {e}")
        print("Available columns:", input_df.columns.tolist())
        print("Expected features:", model.feature_names_in_)
        return None

    # Make prediction
    pred = model.predict(X_input)[0]

    return pred

# Example of constructing a new input using the most common values
# Get the most common values for each column, excluding the SalePrice column
# Specify the columns to exclude
exclude_columns = ['SalePrice', 'MoSold', 'SaleType_New', 'YrSold']

# Get the most common values for each column, excluding the specified columns
# Specify the columns to exclude
exclude_columns = ['SalePrice', 'MoSold', 'SaleType_New', 'YrSold']

# Filter the exclude_columns to include only those that are present in the DataFrame
existing_exclude_columns = [col for col in exclude_columns if col in df.columns]

# Get the most common values for each column, excluding the specified columns
most_common_values = df.drop(columns=existing_exclude_columns).mode().iloc[0]

# Convert the most common values to a dictionary
new_input = most_common_values.to_dict()

# Optional: Modify the input if necessary
new_input['LotFrontage'] = 80  # Example modification

# Print the new input to check its structure
print("New Input for Prediction:")
print(new_input)

# Call the prediction function
prediction = predict_single_input(new_input, model, num_imputer, scaler, encoder, categorical_cols)
if prediction is not None:
    print("Predicted Sale Price:", prediction)