# -*- coding: utf-8 -*-
"""Linear Regressionp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JbE1i5rHlnQ01V9H8sfaQJ9G1K5lnq88
"""

medical_charges_url = 'https://raw.githubusercontent.com/JovianML/opendatasets/master/data/medical-charges.csv'
from urllib.request import urlretrieve
urlretrieve(medical_charges_url, 'medical.csv')

!pip install pandas --quiet
import pandas as pd

!pip install plotly matplotlib seaborn

# Commented out IPython magic to ensure Python compatibility.
import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from urllib.request import urlretrieve
urlretrieve(medical_charges_url, 'medical.csv')

medical_df = pd.read_csv('medical.csv')
medical_df

non_smoker_df = medical_df[medical_df.smoker == 'no']

def rmse(targets, predictions):
    return np.sqrt(np.mean(np.square(targets - predictions)))
def estimate_charges(age, w, b):
    return w * age + b

def try_parameters(w, b):
    ages = non_smoker_df.age
    target = non_smoker_df.charges
    predictions = estimate_charges(ages, w, b)

    plt.plot(ages, predictions, 'r', alpha=0.9);
    plt.scatter(ages, target, s=8,alpha=0.8);
    plt.xlabel('Age');
    plt.ylabel('Charges')
    plt.legend(['Prediction', 'Actual']);

    loss = rmse(target, predictions)
    print("RMSE Loss: ", loss)

try_parameters(320, -3000)

!pip install scikit-learn --quiet
!pip install numpy --quiet

from sklearn.linear_model import LinearRegression
import numpy as np

inputs = non_smoker_df[['age']]
targets = non_smoker_df.charges
print('inputs.shape :', inputs.shape)
print('targes.shape :', targets.shape)
model = LinearRegression()

model.fit(inputs, targets)
model.predict(np.array([[23],
                        [37],
                        [61]]))
predictions = model.predict(inputs)

predictions = model.predict(inputs)
predictions

rmse(targets, predictions)

rmse(targets, predictions)

from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error

sgd_model = SGDRegressor()

# Fit the model to the data
sgd_model.fit(inputs, targets)

# Make predictions
sgd_predictions = sgd_model.predict(inputs)

rmse(targets, sgd_predictions)

smoker_df = medical_df[medical_df.smoker == 'yes']

def parameter(w,b) :
  age = smoker_df.age
  target = smoker_df.charges
  estimated_charge = estimate_charges(age,target)
  plt.plot(age,estimated_charge,'r',alpha='0.9')
  plt.scatter(age,target,s=8,alpha='0.8')
  plt.xlabel('Age');
  plt.ylabel('Charges')
  plt.legend(['Estimate', 'Actual']);

inputs = smoker_df[['age']]
targets = smoker_df.charges
print('inputs.shape :', inputs.shape)
print('targes.shape :', targets.shape)
model = LinearRegression()

model.fit(inputs, targets)
model.predict(np.array([[23],
                        [37],
                        [61]]))
predictions = model.predict(inputs)
loss = rmse(targets,predictions)
print('amount of loss :',loss)